site_name: Экстерн для 1С
nav:
- О модуле:
  - 'Описание': 'index.md'
  - 'Часто задаваемые вопросы': 'FAQ.md'
  - 'Расширение': 'extension.md'
- Отчеты:
  - 'Авторизация': 'features/Авторизация.md'
  - 'ФНС': 'features/Отправка в ФНС.md'
  - 'Росстат': 'features/Отправка в Росстат.md'
  - 'ПФР': 'features/Отправка в ПФР.md'
  - 'ФСС': 'features/Отправка в ФСС.md'
  - 'Список отчетов': 'features/Список отчетов.md'
  - 'Массовая отправка': 'features/Массовая отправка.md'
  - 'Печать': 'features/Печать.md'
- Письма:
  - 'ФНС': 'features/Отправка писем.md'  
  - 'Входящие ФНС': 'features/Получение входящих писем.md'
- Сверки:
  - 'ФНС': 'features/Сверка с ФНС.md' 
- Поддержка:
  - 'Обновление': 'features/Обновления.md' 
  - 'Диагностика неисправностей': 'features/Сохранить информацию о неисправности.md'
  - 'Криптография': 'crypto.md' 
theme: readthedocs