site_name: Экстерн для 1С
nav:
- О модуле:
  - 'Описание': 'index.md'
  - 'Часто задаваемые вопросы': 'FAQ.md'
- Отчеты:
  - 'Авторизация': 'Авторизация.md'
  - 'ФНС': 'Отправка в ФНС.md'
  - 'Росстат': 'Отправка в Росстат.md'
  - 'ПФР': 'Отправка в ПФР.md'
  - 'ФСС': 'Отправка в ФСС.md'
  - 'Список отчетов': 'Список отчетов.md'
  - 'Массовая отправка': 'Массовая отправка.md'
- Письма:
  - 'ФНС': 'Отправка писем.md'  
  - 'Входящие ФНС': 'Получение входящих писем.md'
- Сверки:
  - 'ФНС': 'Сверка с ФНС.md' 
- Поддержка:
  - 'Обновление': 'Обновления.md' 
  - 'Диагностика неисправностей': 'Сохранить информацию о неисправности.md'
  - 'Криптография': 'crypto.md' 
theme: readthedocs